### ISSUE TITLE
exporter??? Faz sentido?

### ISSUE THREAD

**Issue by edimarlnx** [tecsinapse/tecsinapse-exporter#26]
Hoje o projeto se chama tecsinapse-exporter, mas ele é muito mais que um exporter. Também realiza importação de arquivos.

O que acham de se chamar: tecsinapse-spreadsheet ou tecsinapse-calc (Seguindo a linha do [Open/libre] office)?

@filipenevola  @Janario @jpbassinello 

Formulário para votação: https://goo.gl/forms/iX5lvC4zZqv0n1vk2

**Comment by emannuel** [comment]
tecsinapse-file-engine ?

**Comment by filipeportes** [comment]
tecsinapse-poi

poi já é um nome bem conhecido e vai deixar claro que a lib é uma extensão dele.
