### ISSUE TITLE
Export with multiple sheets

### ISSUE THREAD

**Issue by richardsms** [tecsinapse/tecsinapse-exporter#28]

**Comment by edimarlnx** [comment]
@richardsms  estava fazendo uns testes de alguns ajustes e acabei comitando o código de fazer várias planilhas em um mesmo arquivo. 

Se você rodar o teste do arquivo: ExcelCellColorExampleTest#generateManySheetsExample ele vai gerar um exemplo.

https://github.com/tecsinapse/tecsinapse-exporter/commit/462cab5c0147f8a5a1749ce108c6db4542992578
